# This is a basic workflow to help you get started with Actions

name: npm packages publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org 
      - name: 安装主包依赖
      - run: npm i
      - name: 安装子包依赖
      - run: npx lerna run init
      - name: 运行子包测试
      - run: npx lerna run test
      - name: 运行子包构建
      - run: npx lerna run build
      - name: 发布子包
      - run: npx lerna publish from-package --yes
        env:
          registry-url: https://registry.npmjs.org 
